# -*- coding: utf-8 -*-
"""generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JeNZBxE8qNql8_Jgh7Q_vL3nRslPS4TK
"""

from __future__ import annotations

import csv
import os
import random
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from dotenv import load_dotenv

load_dotenv()

from llm_client import make_client, get_model
from schema import Application, CITIES, CURRENT_YEAR

# параметры

TOTAL = 50
QUOTA_CITIES = CITIES[:10]  # ровно 10 городов для квотирования
PER_CITY = TOTAL // len(QUOTA_CITIES)  # 5 заявок на город
OUTPUT_CSV = Path("applications.csv")
CITIES_PNG = Path("cities.png")
SPEC_PNG = Path("specialities.png")
SEED = 42

random.seed(SEED)

SPECIALITY_HINTS = ["Воспитатель детского сада", "Инженер-электрик", "Учитель начальных классов", "Программист",
"Врач-терапевт", "Психолог", "Медицинская сестра", "Учитель математики", "Инженер-строитель", "Бухгалтер", "Юрист"]

COURSE_HINTS = ["Цифровые технологии в профессиональной деятельности", "Управление проектами",
"Педагогика и современные методы обучения", "Финансовый менеджмент и бухгалтерский учёт",
"Медицинские технологии и телемедицина", "Юридическая практика в условиях цифровизации", "Психологическое консультирование"]


def build_prompt(seed_city: str, seed_speciality: str, idx: int) -> str:
    return f"""Ты генерируешь реалистичные синтетические заявки на курсы \
повышения квалификации (ДПО) для российских специалистов.

Сгенерируй ОДНУ заявку со следующими ограничениями:
- Город ОБЯЗАТЕЛЬНО: {seed_city}
- Район/округ: реалистичный район этого города
- Специальность желательно близкая к: {seed_speciality}
  (но ты можешь выбрать любую из разрешённых, если она лучше подходит)
- Желаемый курс: выбери тот, что логично соответствует специальности
- Возраст: от 22 до 65 лет
- Стаж работы: от 0 до 40 лет (должен быть реалистичен для возраста)
- Год окончания вуза: от 1980 до {CURRENT_YEAR}
  (должен быть согласован с возрастом: человек не мог окончить вуз до 22 лет)
- ФИО: реалистичное русское имя (формат: Фамилия Имя Отчество)

Номер заявки (для разнообразия): {idx}
"""


def flatten(app: Application) -> dict:
    return {
        "full_name": app.full_name,
        "age": app.age,
        "city": app.address.city,
        "district": app.address.district,
        "speciality": app.speciality,
        "desired_course": app.desired_course,
        "years_of_experience": app.years_of_experience,
        "graduation_year": app.graduation_year,
    }


def generate_all() -> list[dict]:
    client = make_client()
    model = get_model()

    # Составляем расписание по квотам
    schedule: list[tuple[str, str]] = []
    spec_cycle = SPECIALITY_HINTS.copy()
    random.shuffle(spec_cycle)
    for i, city in enumerate(QUOTA_CITIES):
        for j in range(PER_CITY):
            hint = spec_cycle[(i * PER_CITY + j) % len(spec_cycle)]
            schedule.append((city, hint))
    random.shuffle(schedule)  # перемешиваем, чтобы города не шли блоками

    records: list[dict] = []
    errors: int = 0

    for idx, (city, spec_hint) in enumerate(schedule, start=1):
        prompt = build_prompt(city, spec_hint, idx)
        print(f"[{idx:02d}/{TOTAL}] город={city:20s} hint={spec_hint[:20]} ...", end=" ", flush=True)
        try:
            app: Application = client.chat.completions.create(
                model=model,
                response_model=Application,
                max_retries=3,
                messages=[{"role": "user", "content": prompt}],
                temperature=1.0,
            )
            records.append(flatten(app))
            print("OK")
        except Exception as exc:
            errors += 1
            print(f"ОШИБКА: {exc}")

    print(f"\nГенерация завершена: {len(records)}/50 успешно, {errors} ошибок")
    return records


def save_csv(records: list[dict]) -> None:
    if not records:
        print("Нет данных для сохранения.")
        return
    fieldnames = list(records[0].keys())
    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(records)
    print(f"CSV сохранён: {OUTPUT_CSV} ({len(records)} строк)")


def plot_bar(values: list[str], title: str, out_path: Path, max_pct: float) -> None:
    from collections import Counter
    counts = Counter(values)
    labels = sorted(counts, key=counts.get, reverse=True)
    freqs = [counts[l] for l in labels]
    total = sum(freqs)
    pcts = [f * 100 / total for f in freqs]

    short_labels = [l if len(l) <= 30 else l[:27] + "…" for l in labels]

    fig, ax = plt.subplots(figsize=(10, max(4, len(labels) * 0.55)))
    bars = ax.barh(short_labels[::-1], pcts[::-1], color="#4C72B0")
    ax.axvline(max_pct, color="red", linestyle="--", linewidth=1.2,
               label=f"Порог {max_pct:.0f}%")
    ax.set_xlabel("Доля, %")
    ax.set_title(title)
    ax.legend()
    for bar, pct in zip(bars, pcts[::-1]):
        ax.text(bar.get_width() + 0.3, bar.get_y() + bar.get_height() / 2,
                f"{pct:.1f}%", va="center", fontsize=8)
    plt.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"График сохранён: {out_path}")


def make_charts(records: list[dict]) -> None:
    cities = [r["city"] for r in records]
    specs = [r["speciality"] for r in records]
    plot_bar(cities, "Распределение заявок по городам", CITIES_PNG, max_pct=40)
    plot_bar(specs, "Распределение заявок по специальностям", SPEC_PNG, max_pct=35)


if __name__ == "__main__":
    records = generate_all()
    save_csv(records)
    if records:
        make_charts(records)