# -*- coding: utf-8 -*-
"""schema

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1Gg1Vmmy55TB3iGbgVOE3rdr-wC1ya7
"""

from __future__ import annotations

import datetime
from typing import Literal

from pydantic import BaseModel, field_validator, model_validator


# справочники

CITIES: list[str] = ["Москва", "Санкт-Петербург", "Новосибирск", "Екатеринбург",
"Казань", "Нижний Новгород", "Самара", "Краснодар", "Челябинск", "Красноярск",
"Уфа", "Ростов-на-Дону", "Тюмень", "Курган"]

SPECIALITIES = Literal["Воспитатель детского сада", "Инженер-электрик", "Учитель начальных классов", "Программист",
"Врач-терапевт", "Психолог", "Медицинская сестра", "Учитель математики", "Инженер-строитель", "Бухгалтер", "Юрист"]

COURSES = Literal["Цифровые технологии в профессиональной деятельности", "Управление проектами",
"Педагогика и современные методы обучения", "Финансовый менеджмент и бухгалтерский учёт",
"Медицинские технологии и телемедицина", "Юридическая практика в условиях цифровизации", "Психологическое консультирование"]

CURRENT_YEAR: int = datetime.datetime.now().year


# вложенная модель адреса

class Address(BaseModel):
    city: str
    district: str

    @field_validator("city")
    @classmethod
    def city_must_be_in_list(cls, v: str) -> str:
        if v not in CITIES:
            raise ValueError(
                f"Город '{v}' не входит в допустимый список. "
                f"Допустимые города: {', '.join(CITIES)}"
            )
        return v


# основная модель заявки

class Application(BaseModel):
    full_name: str
    age: int
    address: Address
    speciality: SPECIALITIES  # type: ignore[valid-type]
    desired_course: COURSES  # type: ignore[valid-type]
    years_of_experience: int
    graduation_year: int

    # валидаторы полей

    @field_validator("age")
    @classmethod
    def age_in_range(cls, v: int) -> int:
        if not (22 <= v <= 65):
            raise ValueError(f"Возраст должен быть от 22 до 65, получено {v}")
        return v

    @field_validator("years_of_experience")
    @classmethod
    def experience_in_range(cls, v: int) -> int:
        if not (0 <= v <= 40):
            raise ValueError(
                f"Стаж должен быть от 0 до 40 лет, получено {v}"
            )
        return v

    @field_validator("graduation_year")
    @classmethod
    def graduation_year_in_range(cls, v: int) -> int:
        if not (1980 <= v <= CURRENT_YEAR):
            raise ValueError(
                f"Год окончания вуза должен быть от 1980 до {CURRENT_YEAR}, "
                f"получено {v}"
            )
        return v

    @model_validator(mode="after")
    def graduation_consistent_with_age(self) -> "Application":
        earliest_possible_graduation = CURRENT_YEAR - self.age + 22
        # Нельзя окончить вуз позже, чем сейчас минус (возраст - 22)
        if self.graduation_year > earliest_possible_graduation:
            raise ValueError(
                f"graduation_year ({self.graduation_year}) противоречит возрасту "
                f"({self.age}): максимально возможный год окончания — "
                f"{earliest_possible_graduation}"
            )
        return self