# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_Vi87NTIVCN1HaFM_SJykETLguHTXJ1
"""

from __future__ import annotations

import json
import re
import time
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from llm_client import get_model, make_client
from prompts import (
    IE_SYSTEM, ASPECTS_SYSTEM, DISCOVER_SYSTEM,
    CHUNK_SYSTEM, REDUCE_SYSTEM, JUDGE_SYSTEM,
)
from schema import (
    Review, ReviewBatch, ReviewAspects, AspectScore,
    ChunkSummary, FinalSummary, JudgeReport,
    DiscoveredAspects, FIXED_ASPECTS,
)

client = make_client()
MODEL = get_model()

INPUT_DIR = Path("input")
OUTPUT_DIR = Path("output")

# Утилиты
def load_input(input_dir: Path) -> dict[str, str]:
    files = {}
    for f in sorted(input_dir.glob("*.txt")):
        files[f.stem] = f.read_text(encoding="utf-8")
    print(f"Загружено файлов: {len(files)}: {list(files.keys())}")
    return files


def check_quotes(reviews: list[Review], raw_texts: dict[str, str]) -> int:
    """
    Sanity-check галлюцинаций: проверяет, что первые 30 символов каждой
    цитаты из issue.quote реально есть в исходных текстах.

    Возвращает количество ghost-цитат.
    """
    all_source = "\n".join(raw_texts.values()).lower()
    ghost_count = 0
    ghost_details = []

    for review in reviews:
        for issue in review.issues:
            fragment = issue.quote.strip().lower()[:30]
            if fragment and fragment not in all_source:
                ghost_count += 1
                ghost_details.append({
                    "review_id": review.review_id,
                    "ghost_quote": issue.quote[:120],
                })
                print(f"Ghost quote [{review.review_id}]: «{issue.quote[:60]}»")

    total_quotes = sum(len(r.issues) for r in reviews)
    print(f"\ncheck_quotes: {ghost_count} ghost-цитат из {total_quotes} всего "
          f"({ghost_count/max(total_quotes,1)*100:.1f}%)")

    (OUTPUT_DIR / "ghost_quotes.json").write_text(
        json.dumps(ghost_details, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return ghost_count

# Раунд 1 — Information Extraction
def extract_reviews(text: str) -> list[Review]:
    result = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": IE_SYSTEM},
            {"role": "user", "content": f"Извлеки все отзывы:\n\n{text}"},
        ],
        response_model=ReviewBatch,
        max_retries=3,
        temperature=0.0,
    )
    return result.items


def run_ie(raw_texts: dict[str, str]) -> list[Review]:
    print("РАУНД 1 — Information Extraction")

    all_reviews: list[Review] = []
    valid, errors = 0, 0

    for filename, text in raw_texts.items():
        print(f"\n  Обрабатываем {filename}")
        try:
            reviews = extract_reviews(text)
            all_reviews.extend(reviews)
            valid += len(reviews)
            print(f"{len(reviews)} отзывов")
        except Exception as e:
            errors += 1
            print(f"Ошибка: {e}")

    print(f"\nИтого: {valid} валидных, {errors} с ошибкой")
    out = [r.model_dump(mode="json") for r in all_reviews]
    (OUTPUT_DIR / "reviews.json").write_text(
        json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print("Сохранено: output/reviews.json")
    return all_reviews

# Раунд 2 — Аспектный анализ + тепловая карта
def extract_aspects_for_review(review_id: str, review_text: str) -> ReviewAspects:
    return client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": ASPECTS_SYSTEM},
            {"role": "user", "content": f"Review ID: {review_id}\n\nТекст:\n{review_text}"},
        ],
        response_model=ReviewAspects,
        max_retries=3,
        temperature=0.0,
    )


def run_aspects(reviews: list[Review], raw_texts: dict[str, str]) -> list[ReviewAspects]:
    print("РАУНД 2 — Аспектный анализ")

    all_source = "\n".join(raw_texts.values())
    all_aspects: list[ReviewAspects] = []

    for review in reviews:
        # Находим оригинальный текст по номеру отзыва
        num = review.review_id.replace("review_", "")
        pattern = rf"Review #{num}\s.*?Text:(.*?)(?=Review #\d+|$)"
        match = re.search(pattern, all_source, re.DOTALL)
        review_text = match.group(1).strip() if match else " | ".join(
            i.description for i in review.issues
        )
        try:
            aspects = extract_aspects_for_review(review.review_id, review_text)
            all_aspects.append(aspects)
        except Exception as e:
            print(f"  ✗ {review.review_id}: {e}")

    print(f"Аспекты извлечены для {len(all_aspects)}/{len(reviews)} отзывов")
    out = [a.model_dump(mode="json") for a in all_aspects]
    (OUTPUT_DIR / "aspects.json").write_text(
        json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print("Сохранено: output/aspects.json")
    return all_aspects


def build_heatmap(all_aspects: list[ReviewAspects]) -> None:
    """Тепловая карта: reviews × aspects."""
    print("\nСтроим heatmap")
    review_ids = [ra.review_id for ra in all_aspects]
    arr = np.full((len(review_ids), len(FIXED_ASPECTS)), np.nan)

    for i, ra in enumerate(all_aspects):
        for asp in ra.aspects:
            if asp.aspect in FIXED_ASPECTS and asp.mentioned and asp.score is not None:
                j = FIXED_ASPECTS.index(asp.aspect)
                arr[i, j] = asp.score

    fig, ax = plt.subplots(figsize=(12, max(6, len(review_ids) * 0.35)))
    sns.heatmap(
        arr, mask=np.isnan(arr), annot=True, fmt=".1f",
        cmap="RdYlGn", vmin=1, vmax=5, ax=ax, linewidths=0.3,
        xticklabels=FIXED_ASPECTS, yticklabels=review_ids,
        cbar_kws={"label": "Оценка (1=плохо, 5=отлично)"},
    )
    ax.set_title("Heatmap: оценки аспектов по отзывам (Spotify)", fontsize=14, pad=15)
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "heatmap.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("Сохранено: output/heatmap.png")

# Раунд 2.5 — Autodiscovery
def discover_aspects(all_text: str) -> DiscoveredAspects:
    """Автообнаружение аспектов по всему корпусу отзывов."""
    result = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": DISCOVER_SYSTEM},
            {"role": "user", "content": f"Проанализируй отзывы и найди все темы:\n\n{all_text}"},
        ],
        response_model=DiscoveredAspects,
        max_retries=3,
        temperature=0.0,
    )
    # Вычислим novel_aspect_names
    result.novel_aspect_names = [
        a.name for a in result.items if not a.in_fixed_list
    ]
    return result


def run_autodiscovery(raw_texts: dict[str, str]) -> DiscoveredAspects:
    print("РАУНД 2.5")

    all_text = "\n\n".join(raw_texts.values())
    result = discover_aspects(all_text)

    novel = [a for a in result.items if not a.in_fixed_list]
    print(f"Обнаружено аспектов: {len(result.items)}, новых: {len(novel)}")
    for a in novel:
        print(f"{a.name}: «{a.example_quote[:60]}» (freq={a.frequency})")

    # Сравнение с фиксированным списком
    all_names = {a.name for a in result.items}
    missing = set(FIXED_ASPECTS) - all_names
    if missing:
        print(f"Из Literal не обнаружены: {sorted(missing)}")

    (OUTPUT_DIR / "autodiscovery.json").write_text(
        result.model_dump_json(indent=2), encoding="utf-8"
    )
    print("Сохранено: output/autodiscovery.json")
    return result

# Раунд 3 — Map-Reduce
def summarize_chunk(chunk_id: str, chunk_text: str, n_reviews: int) -> ChunkSummary:
    return client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": CHUNK_SYSTEM},
            {"role": "user", "content": (
                f"Chunk ID: {chunk_id}\nОтзывов: {n_reviews}\n\n{chunk_text}"
            )},
        ],
        response_model=ChunkSummary,
        max_retries=3,
        temperature=0.0,
    )

def _reduce_with_system(chunk_summaries, total_reviews, system_prompt):
    chunks_text = json.dumps(
        [s.model_dump(mode="json") for s in chunk_summaries],
        ensure_ascii=False, indent=2
    )
    avg = sum(s.avg_rating for s in chunk_summaries) / len(chunk_summaries)
    return client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": (
                f"Всего отзывов: {total_reviews}\n"
                f"Средний рейтинг: {avg:.2f}\n\n"
                f"Частичные саммари:\n{chunks_text}"
            )},
        ],
        response_model=FinalSummary,
        max_retries=3,
        temperature=0.0,
    )

def reduce_summaries(chunk_summaries: list[ChunkSummary], total_reviews: int) -> FinalSummary:
    chunks_text = json.dumps(
        [s.model_dump(mode="json") for s in chunk_summaries],
        ensure_ascii=False, indent=2
    )
    avg = sum(s.avg_rating for s in chunk_summaries) / len(chunk_summaries)
    return client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": REDUCE_SYSTEM},
            {"role": "user", "content": (
                f"Всего отзывов: {total_reviews}\n"
                f"Средний рейтинг: {avg:.2f}\n\n"
                f"Частичные саммари:\n{chunks_text}"
            )},
        ],
        response_model=FinalSummary,
        max_retries=3,
        temperature=0.0,
    )


def run_map_reduce(reviews: list[Review], raw_texts: dict[str, str]) -> FinalSummary:
    print("РАУНД 3 — Map-Reduce")

    # Разбиваем по блокам "Review #N"
    all_text = "\n\n".join(raw_texts.values())
    review_blocks = [b.strip() for b in re.split(r'(?=Review #\d+)', all_text) if b.strip()]

    CHUNK_SIZE = 10
    chunks = [
        (f"chunk_{i//CHUNK_SIZE + 1}", review_blocks[i:i+CHUNK_SIZE])
        for i in range(0, len(review_blocks), CHUNK_SIZE)
    ]
    print(f"Чанков: {len(chunks)}")

    # MAP
    chunk_summaries: list[ChunkSummary] = []
    for chunk_id, blocks in chunks:
        chunk_text = "\n\n".join(blocks)
        print(f"MAP {chunk_id}: {len(blocks)} отзывов")
        s = summarize_chunk(chunk_id, chunk_text, len(blocks))
        chunk_summaries.append(s)
        print(f"avg_rating={s.avg_rating:.2f}")

    # REDUCE
    print("\n REDUCE")
    final = reduce_summaries(chunk_summaries, len(reviews))

    (OUTPUT_DIR / "summary.json").write_text(
        final.model_dump_json(indent=2), encoding="utf-8"
    )
    print("Сохранено: output/summary.json")
    return final

# Раунд 5 — LLM-as-Judge
def build_evidence_packet(reviews: list[Review], summary: FinalSummary) -> str:
    lines = ["## Рекомендации (которые оцениваем)"]
    for item in summary.action_items:
        lines.append(f"  - {item}")

    lines.append("\n## Жалобы из отзывов (исходные данные)")
    for r in reviews:
        for issue in r.issues:
            lines.append(f"[{r.review_id}, rating={r.rating}] "
                         f"[{issue.category}] {issue.description} | «{issue.quote[:80]}»")
    return "\n".join(lines)


def judge(reviews: list[Review], summary: FinalSummary) -> JudgeReport:
    packet = build_evidence_packet(reviews, summary)
    return client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": JUDGE_SYSTEM},
            {"role": "user", "content": packet},
        ],
        response_model=JudgeReport,
        max_retries=3,
        temperature=0.0,
    )


def run_judge(reviews: list[Review], summary: FinalSummary) -> JudgeReport:
    print("РАУНД 5 — LLM-as-Judge")

    report = judge(reviews, summary)
    counts = {"supported": 0, "weakly_supported": 0, "not_supported": 0}
    for v in report.verdicts:
        counts[v.support] += 1

    print(f"supported: {counts['supported']}")
    print(f"weakly_supported: {counts['weakly_supported']}")
    print(f"not_supported: {counts['not_supported']}")
    print(f"overall_score: {report.overall_score:.2f}")
    print(f"needs_revision: {report.needs_revision}")

    (OUTPUT_DIR / "judge_report.json").write_text(
        report.model_dump_json(indent=2), encoding="utf-8"
    )
    print("Сохранено: output/judge_report.json")

    if report.needs_revision:
        print("\noverall_score < 0.7 — переписываем REDUCE промпт и прогоняем снова")
        # Revision pass будет вызван из analyze()

    return report

# Главный конвейер
def analyze(input_path: Path = INPUT_DIR) -> None:

    t0 = time.time()
    OUTPUT_DIR.mkdir(exist_ok=True)

    print("SPOTIFY REVIEW ANALYSIS PIPELINE")

    # 0. Загружаем данные
    raw_texts = load_input(input_path)

    # 1. IE
    reviews = run_ie(raw_texts)

    # Sanity-check галлюцинаций
    ghost_count = check_quotes(reviews, raw_texts)

    # 2. Аспекты + heatmap
    all_aspects = run_aspects(reviews, raw_texts)
    if all_aspects:
        build_heatmap(all_aspects)

    # 2.5. Autodiscovery
    autodiscovery = run_autodiscovery(raw_texts)

    # 3. Map-Reduce
    summary = run_map_reduce(reviews, raw_texts)

    # 5. Judge
    report = run_judge(reviews, summary)

    if report.needs_revision:
        from prompts import REDUCE_SYSTEM as BASE_REDUCE
        improved = BASE_REDUCE + (
            "\n\nВАЖНО (revision pass): каждый action_item ОБЯЗАН содержать "
            "конкретную ссылку на отзывы (например: '7 из 30 отзывов упоминают'). "
            "Избегай расплывчатых формулировок."
        )
        # Повторный map-reduce с улучшенным промптом
        all_text = "\n\n".join(raw_texts.values())
        review_blocks = [b.strip() for b in re.split(r'(?=Review #\d+)', all_text) if b.strip()]
        CHUNK_SIZE = 10
        chunk_summaries = []
        for i in range(0, len(review_blocks), CHUNK_SIZE):
            blocks = review_blocks[i:i+CHUNK_SIZE]
            s = summarize_chunk(f"retry_chunk_{i//CHUNK_SIZE+1}", "\n\n".join(blocks), len(blocks))
            chunk_summaries.append(s)

        # Переопределяем REDUCE_SYSTEM временно
        import prompts
        original = prompts.REDUCE_SYSTEM
        prompts.REDUCE_SYSTEM = improved
        summary = _reduce_with_system(chunk_summaries, len(reviews), improved)
        prompts.REDUCE_SYSTEM = original

        (OUTPUT_DIR / "summary_revised.json").write_text(
            summary.model_dump_json(indent=2), encoding="utf-8"
        )
        report = run_judge(reviews, summary)

    # Итоговые метрики
    elapsed = time.time() - t0
    total_quotes = sum(len(r.issues) for r in reviews)
    meta = {
        "reviews_processed": len(reviews),
        "validation_errors": 0,
        "ghost_quotes": ghost_count,
        "total_quotes": total_quotes,
        "ghost_rate_pct": round(ghost_count / max(total_quotes, 1) * 100, 1),
        "judge_overall_score": report.overall_score,
        "autodiscovery_novel_aspects": autodiscovery.novel_aspect_names,
        "elapsed_seconds": round(elapsed, 1),
    }
    (OUTPUT_DIR / "run_meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    print("ИТОГИ ПРОГОНА")
    print(f"Отзывов обработано: {meta['reviews_processed']}")
    print(f"Ghost-цитат: {ghost_count} / {total_quotes} ({meta['ghost_rate_pct']}%)")
    print(f"Judge overall_score: {report.overall_score:.2f}")
    print(f"Новых аспектов (autodiscovery): {len(autodiscovery.novel_aspect_names)}")
    print(f"Время: {elapsed:.1f}s")


if __name__ == "__main__":
    analyze()