# -*- coding: utf-8 -*-
"""schema

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlJi417p5yBO319Bt45MCoy04ye-k9JX
"""

from __future__ import annotations

from datetime import date
from typing import Literal, Optional

from pydantic import BaseModel, Field, field_validator

# Раунд 1 — Information Extraction

class Issue(BaseModel):
    """Конкретная проблема или похвала, упомянутая в отзыве."""
    description: str = Field(..., description="Краткое описание (1-2 предложения)")
    quote: str = Field(..., description="Точная цитата из отзыва")
    sentiment: Literal["positive", "negative", "neutral"]
    category: Literal[
        "производительность", "дизайн", "поддержка",
        "цена", "реклама", "надёжность", "другое"
    ]


class Review(BaseModel):
    """Структурированный отзыв."""
    review_id: str
    app_name: str
    rating: int = Field(..., ge=1, le=5)
    review_date: Optional[date] = None
    issues: list[Issue] = Field(default_factory=list)
    overall_sentiment: Literal["positive", "negative", "neutral", "mixed"]
    would_recommend: Optional[bool] = None

    @field_validator("review_date")
    @classmethod
    def date_not_in_future(cls, v: Optional[date]) -> Optional[date]:
        if v is not None and v > date.today():
            raise ValueError(f"Дата отзыва {v} позже сегодняшней")
        return v

    @field_validator("issues")
    @classmethod
    def at_least_one_issue(cls, v: list[Issue]) -> list[Issue]:
        if len(v) == 0:
            raise ValueError("Должен быть хотя бы один issue")
        return v


class ReviewBatch(BaseModel):
    """Список отзывов из одного файла."""
    items: list[Review]

# Раунд 2 — Аспектный анализ
FIXED_ASPECTS: list[str] = [
    "производительность", "дизайн", "поддержка",
    "цена", "реклама", "надёжность",
]


class AspectScore(BaseModel):
    """Оценка одного аспекта."""
    aspect: str
    score: Optional[float] = Field(None, ge=1.0, le=5.0)
    evidence: Optional[str] = None
    mentioned: bool

    @field_validator("score")
    @classmethod
    def score_when_mentioned(cls, v: Optional[float], info) -> Optional[float]:
        if info.data.get("mentioned") and v is None:
            raise ValueError("score обязателен если mentioned=True")
        return v


class ReviewAspects(BaseModel):
    """Аспектные оценки для одного отзыва."""
    review_id: str
    aspects: list[AspectScore]

# Раунд 2.5 — Autodiscovery аспектов
class DiscoveredAspect(BaseModel):
    name: str = Field(..., description="Краткое название (1-3 слова)")
    description: str
    frequency: int = Field(..., ge=1)
    example_quote: str
    in_fixed_list: bool


class DiscoveredAspects(BaseModel):
    """Результат автообнаружения аспектов."""
    items: list[DiscoveredAspect]
    novel_aspect_names: list[str] = Field(
        default_factory=list,
        description="Названия аспектов, которых нет в фиксированном списке"
    )

# Раунд 3 — Map-Reduce
class ChunkSummary(BaseModel):
    """Саммари одного чанка (MAP-фаза)."""
    chunk_id: str
    top_issues: list[str] = Field(..., description="3-5 главных тем")
    sentiment_distribution: dict[str, int]
    avg_rating: float = Field(..., ge=1.0, le=5.0)
    key_quote: str


class FinalSummary(BaseModel):
    """Финальное саммари (REDUCE-фаза)."""
    total_reviews: int
    avg_rating: float
    top_positive_themes: list[str]
    top_negative_themes: list[str]
    critical_issues: list[str]
    action_items: list[str] = Field(..., description="Рекомендации команде")
    executive_summary: str

# Раунд 5 — LLM-as-judge
class ActionVerdict(BaseModel):
    action: str
    support: Literal["supported", "weakly_supported", "not_supported"]
    evidence: list[str] = Field(default_factory=list)
    comment: str


class JudgeReport(BaseModel):
    overall_score: float = Field(..., ge=0.0, le=1.0)
    verdicts: list[ActionVerdict]
    ghost_quotes_found: int = Field(..., ge=0)
    summary: str
    needs_revision: bool = False

    @field_validator("needs_revision")
    @classmethod
    def set_revision(cls, v: bool, info) -> bool:
        return info.data.get("overall_score", 1.0) < 0.7